
server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: studentModule
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: courseModule
          uri: lb://course-service
          predicates:
            - Path=/course/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka