
server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: studentModule
          uri: http://localhost:8081
          predicates:
            - Path=/student/**
        - id: courseModule
          uri: http://localhost:8082
          predicates:
            - Path=/course/**
          filters:
            - name: RequestSize
              args:
                MaxSize: 5000000

