server:
  port: 8082
spring:
  application:
    name: student-service

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/db-student?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver



#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost